FROM node:20-alpine

WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ ./

ARG NEXT_PUBLIC_CONTRACT_ADDRESS
ARG NEXT_PUBLIC_GENLAYER_RPC_URL=https://studio.genlayer.com/api
ARG NEXT_PUBLIC_GENLAYER_CHAIN_ID=61999
ARG NEXT_PUBLIC_GENLAYER_CHAIN_NAME=GenLayer Studio
ARG NEXT_PUBLIC_GENLAYER_SYMBOL=GEN

ENV NEXT_PUBLIC_CONTRACT_ADDRESS=$NEXT_PUBLIC_CONTRACT_ADDRESS
ENV NEXT_PUBLIC_GENLAYER_RPC_URL=$NEXT_PUBLIC_GENLAYER_RPC_URL
ENV NEXT_PUBLIC_GENLAYER_CHAIN_ID=$NEXT_PUBLIC_GENLAYER_CHAIN_ID
ENV NEXT_PUBLIC_GENLAYER_CHAIN_NAME=$NEXT_PUBLIC_GENLAYER_CHAIN_NAME
ENV NEXT_PUBLIC_GENLAYER_SYMBOL=$NEXT_PUBLIC_GENLAYER_SYMBOL

RUN npm run build

EXPOSE 3000

CMD ["sh", "-c", "node_modules/.bin/next start -H 0.0.0.0 -p ${PORT:-3000}"]
